# Generated by Django 5.2 on 2025-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
